### ISSUE TITLE
Ошибка установки с Python 3.8.1

### ISSUE THREAD

**Issue by Beloslav13** [suguby/astrobox#8]
Попытался установить astrobox с Python 3.8.1 в чистом виртуальном окружении, но получил ошибку.
`EOFError: EOF when reading a line
    ----------------------------------------
`
`ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`
Решил проблему поставив Python 3.7.4.

OC: Windows 10

**Comment by suguby** [comment]
с версии 1.5.0 перешли на pygame 2.0 - он корректно работает с py38
